### ISSUE TITLE
Add documentation to call_heideltime 

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/xtas#105]
The call_heideltime() function in tasks/_heideltime.py is undocumented.

**Comment by larsmans** [comment]
Do you mean it needs a docstring? It's the implementation for `xtas.tasks.single.heideltime`, which has the user-facing documentation, and I chose not to repeat it because the function is short and simple.

**Comment by LourensVeen** [comment]
Yes, that's what I meant. I hadn't realised that `xtas.tasks.single.heideltime` documents it, but you're right, and the function and argument names make it pretty clear what's happening anyway. The only thing that's not obvious is what it returns.

I guess I'm also a bit confused by what is and isn't private. The idea is that `xtas.tasks._heideltime` is a private module within xtas, so it's not supposed to be called by the user of xtas, right? But then `call_heideltime()` is a public function of that module (as opposed to say '_heideltime_dir'), so it is supposed to be called by its users, in this case `single`. PEP 257 says to document all public functions, which I think would cover a public function of a private module, so from that perspective...

**Comment by larsmans** [comment]
That's right, it's the public interface of a private module. Think impl/detail namespaces in C++ header libs.

I'll add a short docstring.

**Comment by LourensVeen** [comment]
Ah, that analogy clarifies it perfectly :-). Thanks!

**Comment by larsmans** [comment]
Put in a very minimal docstring, because I just expanded the public docstring and didn't want to repeat it.

**Comment by LourensVeen** [comment]
Nice, looks great now!
