### ISSUE TITLE
Store results as child documents?

### ISSUE THREAD

**Issue by vanatteveldt** [NLeSC/xtas#17]
In the current implementation, xtas results are stored in a 'xtas_results' property on the original document. In the meeting of 13 Feb, we discussed the possibility of storing them as child documents instead. 

Benefits of child documents:
- simpler documents, as each document only represents one type of data. 
- easier to GET/PUT/DELETE single results and to clear a whole type of results
- explicit mapping for each result type, giving options to influence indexing etc.

Benefits of property:
- simpler structure, no additional documents are created
- somewhat easier to get all results for a document

Open questions (raised by Daan during the meeting):
- is there a performance hit when using child documents rather than properties?
- can all needed queries be represented as has_child/has_parent queries?

**Comment by larsmans** [comment]
Closing this as fixed by #9.
